spring:
#  main:
#    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    defer-datasource-initialization: true


#
#logging:
#  level:
#    org:
#      springframework: ERROR


